[package]
name = "vaktija"
version = "0.1.0"
authors = ["Hamza Muric <hamzamuric9@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
serde = "*"
serde_json = "*"
chrono = "0.4.10"
colored = "*"
